In [2]:
import pandas as pd
import numpy as np
import yfinance as yf


# 下載股票數據
ticker = 'AAPL'  # 這裡使用蘋果公司（AAPL）作為例子
start_date = '2020-01-01'
end_date = '2023-12-01'
data = yf.download(ticker, start=start_date, end=end_date)

# 計算MACD指標的函數
def calculate_macd(df, short_window=12, long_window=26, signal_window=9):
    df['EMA12'] = df['Close'].ewm(span=short_window, min_periods=short_window, adjust=False).mean()
    df['EMA26'] = df['Close'].ewm(span=long_window, min_periods=long_window, adjust=False).mean()
    df['MACD'] = df['EMA12'] - df['EMA26']
    df['Signal_Line'] = df['MACD'].ewm(span=signal_window, min_periods=signal_window, adjust=False).mean()
    df['MACD_Histogram'] = df['MACD'] - df['Signal_Line']
    return df

# 調用計算MACD指標的函數
data = calculate_macd(data)

# 打印出計算後的數據，這裡只打印最後幾行
# print(data[['Close', 'EMA12', 'EMA26', 'MACD', 'Signal_Line', 'MACD_Histogram']].tail(20))
data

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,EMA12,EMA26,MACD,Signal_Line,MACD_Histogram
Date,,,,,,,,,,,
2020-01-02,74.059998,75.150002,73.797501,75.087502,72.960464,135480400,NaN,NaN,NaN,NaN,NaN
2020-01-03,74.287498,75.144997,74.125000,74.357498,72.251144,146322800,NaN,NaN,NaN,NaN,NaN
2020-01-06,73.447502,74.989998,73.187500,74.949997,72.826859,118387200,NaN,NaN,NaN,NaN,NaN
2020-01-07,74.959999,75.224998,74.370003,74.597504,72.484344,108872000,NaN,NaN,NaN,NaN,NaN
2020-01-08,74.290001,76.110001,74.290001,75.797501,73.650345,132079200,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2023-11-24,190.869995,190.899994,189.250000,189.970001,189.470901,24048300,187.437909,183.340279,4.097631,3.303983,0.793648
2023-11-27,189.919998,190.669998,188.899994,189.789993,189.291367,40552600,187.799768,183.818035,3.981733,3.439533,0.542200
2023-11-28,189.779999,191.080002,189.399994,190.399994,189.899765,38415400,188.199803,184.305588,3.894215,3.530470,0.363746
2023-11-29,190.899994,192.089996,188.970001,189.369995,188.872482,43014200,188.379833,184.680729,3.699104,3.564196,0.134907
2023-11-30,189.839996,190.320007,188.190002,189.949997,189.450958,48794400,188.621396,185.071045,3.550351,3.561427,-0.011076